### ISSUE TITLE
Cannot compile on 5.4.52

### ISSUE THREAD

**Issue by neheb** [namjaejeon/linux-exfat-oot#8]
```
make[3]: Entering directory '/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.4.52'
  CC [M]  /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.o
/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:296:9: error: macro "__fsparam" passed 5 arguments, but takes just 4
  296 |     NULL),
      |         ^
In file included from /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:9:
./include/linux/fs_parser.h:118: note: macro "__fsparam" defined here
  118 | #define __fsparam(TYPE, NAME, OPT, FLAGS) \
      | 
/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:295:2: error: '__fsparam' undeclared here (not in a function)
  295 |  __fsparam(NULL, "utf8",   Opt_utf8, fs_param_deprecated,
      |  ^~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:298:9: error: macro "__fsparam" passed 5 arguments, but takes just 4
  298 |     NULL),
      |         ^
In file included from /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:9:
./include/linux/fs_parser.h:118: note: macro "__fsparam" defined here
  118 | #define __fsparam(TYPE, NAME, OPT, FLAGS) \
      | 
/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:300:30: error: macro "__fsparam" passed 5 arguments, but takes just 4
  300 |     fs_param_deprecated, NULL),
      |                              ^
In file included from /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:9:
./include/linux/fs_parser.h:118: note: macro "__fsparam" defined here
  118 | #define __fsparam(TYPE, NAME, OPT, FLAGS) \
      | 
/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:302:30: error: macro "__fsparam" passed 5 arguments, but takes just 4
  302 |     fs_param_deprecated, NULL),
      |                              ^
In file included from /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/exfat-5.8.4/super.c:9:
./include/linux/fs_parser.h:118: note: macro "__fsparam" defined here
  118 | #define __fsparam(TYPE, NAME, OPT, FLAGS) \

```

**Comment by namjaejeon** [comment]
FIXED(https://github.com/namjaejeon/linux-exfat-oot/commit/93e2334e76b685fe92114a0db6f6ca43e94f19cb)
Thanks for your reporting!!
