### ISSUE TITLE
release 5.12.3 failed to build on kernel 4.19

### ISSUE THREAD

**Issue by 1715173329** [namjaejeon/linux-exfat-oot#24]
Kernel version:
```
$ uname -r
4.19.0-9-amd64
```
Build log:
```
$ make
make -C /lib/modules/4.19.0-9-amd64/build M=/home/CN_SZTL/linux-exfat-oot modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
  CC [M]  /home/CN_SZTL/linux-exfat-oot/inode.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/namei.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/dir.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/super.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/fatent.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/cache.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/nls.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/misc.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/file.o
  CC [M]  /home/CN_SZTL/linux-exfat-oot/balloc.o
/home/CN_SZTL/linux-exfat-oot/balloc.c: In function ‘exfat_trim_fs’:
/home/CN_SZTL/linux-exfat-oot/balloc.c:325:7: error: implicit declaration of function ‘fatal_signal_pending’; did you mean ‘mod_timer_pending’? [-Werror=implicit-function-declaration]
   if (fatal_signal_pending(current)) {
       ^~~~~~~~~~~~~~~~~~~~
       mod_timer_pending
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309: /home/CN_SZTL/linux-exfat-oot/balloc.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/home/CN_SZTL/linux-exfat-oot] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make: *** [Makefile:21: all] Error 2
```

**Comment by namjaejeon** [comment]
I have applied #25 into #exfat-next branch. It will be merged into #master soon.

**Comment by 1715173329** [comment]
Thanks so much!
